import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f7f4ee',
  '--slot4-page-text': '#1f2430',
  '--slot4-panel-bg': '#efe7d7',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#677083',
  '--slot4-soft-muted-text': '#8a91a1',
  '--slot4-accent': '#aa2b1d',
  '--slot4-accent-fill': '#cc561e',
  '--slot4-accent-soft': '#f3cf7a',
  '--slot4-on-accent': '#fff8ef',
  '--slot4-dark-bg': '#2f3642',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e6dcc8',
  '--slot4-cream': '#fffaf1',
  '--slot4-warm': '#f2ecdf',
  '--slot4-lavender': '#f5f1e6',
  '--slot4-gray': '#ebe4d5',
  '--slot4-body-gradient': 'linear-gradient(180deg, rgba(255,255,255,0.72) 0%, rgba(247,244,238,1) 100%)',
  '--editable-page-bg': '#f7f4ee',
  '--editable-page-text': '#1f2430',
  '--editable-container': '1180px',
  '--editable-border': '#ddd2bd',
  '--editable-nav-bg': '#2f3642',
  '--editable-nav-text': '#fff9f2',
  '--editable-nav-active': '#f3cf7a',
  '--editable-nav-active-text': '#1f2430',
  '--editable-cta-bg': '#cc561e',
  '--editable-cta-text': '#fffaf1',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#21262f',
  '--editable-footer-text': '#fff8ef',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_14px_40px_rgba(38,31,20,0.08)]',
  shadowStrong: 'shadow-[0_28px_70px_rgba(26,21,15,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(47,54,66,0.08),rgba(47,54,66,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-start',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'text-[11px] font-bold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-bold leading-[0.95] tracking-[-0.05em] sm:text-5xl lg:text-[3.9rem]',
    sectionTitle: 'text-3xl font-bold tracking-[-0.04em] sm:text-4xl',
    body: 'text-base leading-8',
  },
  surface: {
    card: `rounded-[1.6rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.7rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.35rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_18px_40px_rgba(30,26,18,0.16)]',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep the full redesign inside src/editable only.',
  'Use category-first discovery, strong search UI, and a bold classified-directory rhythm.',
  'Preserve post links via postHref() and keep all real feed data intact.',
  'Mix featured, compact, list, image-first, and horizontal card styles across sections.',
  'Always render safely when summary, category, image, or optional fields are missing.',
] as const
